# test installation of the script on pull request and merge
name: Install Script Workflow

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Minor hack to remove signup prompt
        run: sed -i.bak '/\$INSTALL_DIRECTORY\/turso auth signup/d' install.sh && rm install.sh.bak

      - name: Run Install Script
        run: bash install.sh

      - name: Verify installation
        run: $HOME/.turso/turso --version
